# Generated by Django 5.1 on 2026-03-07 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_visibility_from_is_public(apps, schema_editor):
    """Backfill enum-based visibility from legacy boolean column values.

    Args:
        apps (Apps): Historical app registry provided by Django migrations.
        schema_editor (BaseDatabaseSchemaEditor): Schema editor passed by migration
            runtime. Not used directly in this data migration.
    """
    Kudos = apps.get_model("accounts", "Kudos")
    Kudos.objects.filter(is_public=True).update(visibility="public")
    Kudos.objects.filter(is_public=False).update(visibility="private")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='kudos',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('team', 'Team'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.RunPython(
            backfill_visibility_from_is_public,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='kudos',
            name='is_public',
        ),
        migrations.CreateModel(
            name='KudosTargetTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kudos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_targets', to='accounts.kudos')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_targets', to='accounts.team')),
            ],
        ),
        migrations.AddField(
            model_name='kudos',
            name='target_teams',
            field=models.ManyToManyField(blank=True, related_name='targeted_kudos', through='accounts.KudosTargetTeam', to='accounts.team'),
        ),
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['visibility', '-created_at'], name='accounts_ku_visibil_1bee31_idx'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='kudostargetteam',
            index=models.Index(fields=['team', 'created_at'], name='accounts_ku_team_id_10d39e_idx'),
        ),
        migrations.AddIndex(
            model_name='kudostargetteam',
            index=models.Index(fields=['kudos', 'created_at'], name='accounts_ku_kudos_i_6da077_idx'),
        ),
        migrations.AddConstraint(
            model_name='kudostargetteam',
            constraint=models.UniqueConstraint(fields=('kudos', 'team'), name='uniq_kudos_target_team'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'role'], name='accounts_te_team_id_04d609_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'role'], name='accounts_te_user_id_ff54b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='uniq_team_member'),
        ),
    ]
