# Generated by Django 5.1 on 2026-03-07 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kudoscomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kudos',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kudos',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kudos',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kudos',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kudos_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kudos',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kudos',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['is_approved', '-created_at'], name='accounts_ku_is_appr_c44cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['is_archived', '-created_at'], name='accounts_ku_is_arch_f540a1_idx'),
        ),
    ]
