# Generated by Django 5.1 on 2026-03-19 12:50

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_event_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='kudosrecipient',
            new_name='accounts_ku_user_id_59a169_idx',
            old_name='accounts_ku_user_id_f2a198_idx',
        ),
        migrations.RenameIndex(
            model_name='kudosrecipient',
            new_name='accounts_ku_kudos_i_cf8577_idx',
            old_name='accounts_ku_kudos_i_6d23ab_idx',
        ),
    ]
