# Generated by Django 5.1 on 2026-03-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team_teammembership_remove_kudos_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='accounts.team'),
        ),
    ]
