# Generated by Django 5.1 on 2026-03-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_active_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KudosComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_comments', to=settings.AUTH_USER_MODEL)),
                ('kudos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.kudos')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['kudos', 'created_at'], name='accounts_ku_kudos_i_c315e5_idx'), models.Index(fields=['author', 'created_at'], name='accounts_ku_author__effb19_idx')],
            },
        ),
    ]
